# Generated by Django 2.1.11 on 2019-11-21 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20191115_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(unique=True)),
                ('hora_inicio', models.TimeField(unique=True)),
                ('hora_fim', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDisciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=20)),
                ('dias_aula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.DiasSemana')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Disciplinas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
