# Generated by Django 2.1.11 on 2019-11-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diassemana_userdisciplinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdisciplinas',
            name='dias_aula',
        ),
        migrations.AddField(
            model_name='userdisciplinas',
            name='dia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdisciplinas',
            name='hora_fim',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='userdisciplinas',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userdisciplinas',
            name='sala',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='DiasSemana',
        ),
    ]
