# Generated by Django 2.1.11 on 2019-12-02 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20191121_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('mensagem', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='disciplinas',
            name='duracao',
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='carga_horaria',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='codigo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdisciplinas',
            name='dia',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdisciplinas',
            name='hora_fim',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userdisciplinas',
            name='hora_inicio',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
